export const DATA = [
    {
        "id": 5772352389402,
        "user_id": 422,
        "shopify_order_number": 1605,
        "customer_id": 7705583943962,
        "price": 106.72,
        "financial_status": "paid",
        "order_status": "Pending",
        "delivery_method": "Standard",
        "order_type": "Regular",
        "quantity_of_sheets": 1,
        "credit_used": null,
        "has_low_dpi": 0,
        "is_local_pickup": 0,
        "cancelled": 0,
        "credits_used": 0,
        "created_at": "December 28, 2023 2:06 am",
        "updated_at": "2023-12-28T07:06:27.000000Z",
        "notes": null,
        "sheets_download_status": "Pre-Rendering",
        "shopify_customer_name": null,
        "line_items_sum_quantity": "4",
        "edit_link": "https://zainab1sep.myshopify.com/apps/ganging-tool/editor/5772352389402?edit=true&edit_link=true",
        "customer": {
            "id": 7705583943962,
            "name": "znb khan"
        },
        "user": {
            "id": 422,
            "name": "zainab1sep.myshopify.com",
            "shop_name": "zainab1sep",
            "email": "shop@zainab1sep.myshopify.com",
            "contact_email": "zainabrahim089@gmail.com",
            "email_verified_at": null,
            "created_at": "2023-12-18T09:27:14.000000Z",
            "updated_at": "2023-12-28T07:09:20.000000Z",
            "shopify_grandfathered": 0,
            "shopify_namespace": null,
            "shopify_freemium": 0,
            "plan_id": 5,
            "timezone": "America/New_York",
            "exists": 1,
            "deleted_at": null,
            "password_updated_at": "2023-12-18",
            "theme_support_level": 1,
            "currency": "₨"
        }
    },
    {
        "id": 5772349636890,
        "user_id": 422,
        "shopify_order_number": 1604,
        "customer_id": 7705583943962,
        "price": 26.68,
        "financial_status": "paid",
        "order_status": "Pending",
        "delivery_method": "Standard",
        "order_type": "Regular",
        "quantity_of_sheets": 1,
        "credit_used": null,
        "has_low_dpi": 0,
        "is_local_pickup": 0,
        "cancelled": 0,
        "credits_used": 0,
        "created_at": "December 28, 2023 2:04 am",
        "updated_at": "2023-12-28T07:05:28.000000Z",
        "notes": null,
        "sheets_download_status": "Ready For Download",
        "shopify_customer_name": null,
        "line_items_sum_quantity": "1",
        "edit_link": "https://zainab1sep.myshopify.com/apps/ganging-tool/editor/5772349636890?edit=true&edit_link=true",
        "customer": {
            "id": 7705583943962,
            "name": "znb khan"
        },
        "user": {
            "id": 422,
            "name": "zainab1sep.myshopify.com",
            "shop_name": "zainab1sep",
            "email": "shop@zainab1sep.myshopify.com",
            "contact_email": "zainabrahim089@gmail.com",
            "email_verified_at": null,
            "created_at": "2023-12-18T09:27:14.000000Z",
            "updated_at": "2023-12-28T07:09:20.000000Z",
            "shopify_grandfathered": 0,
            "shopify_namespace": null,
            "shopify_freemium": 0,
            "plan_id": 5,
            "timezone": "America/New_York",
            "exists": 1,
            "deleted_at": null,
            "password_updated_at": "2023-12-18",
            "theme_support_level": 1,
            "currency": "₨"
        }
    },
    {
        "id": 5772346556698,
        "user_id": 422,
        "shopify_order_number": 1603,
        "customer_id": 7705583943962,
        "price": 26.68,
        "financial_status": "paid",
        "order_status": "Pending",
        "delivery_method": "Standard",
        "order_type": "Regular",
        "quantity_of_sheets": 1,
        "credit_used": null,
        "has_low_dpi": 0,
        "is_local_pickup": 0,
        "cancelled": 0,
        "credits_used": 0,
        "created_at": "December 28, 2023 2:03 am",
        "updated_at": "2023-12-28T07:04:01.000000Z",
        "notes": null,
        "sheets_download_status": "Ready For Download",
        "shopify_customer_name": null,
        "line_items_sum_quantity": "1",
        "edit_link": "https://zainab1sep.myshopify.com/apps/ganging-tool/editor/5772346556698?edit=true&edit_link=true",
        "customer": {
            "id": 7705583943962,
            "name": "znb khan"
        },
        "user": {
            "id": 422,
            "name": "zainab1sep.myshopify.com",
            "shop_name": "zainab1sep",
            "email": "shop@zainab1sep.myshopify.com",
            "contact_email": "zainabrahim089@gmail.com",
            "email_verified_at": null,
            "created_at": "2023-12-18T09:27:14.000000Z",
            "updated_at": "2023-12-28T07:09:20.000000Z",
            "shopify_grandfathered": 0,
            "shopify_namespace": null,
            "shopify_freemium": 0,
            "plan_id": 5,
            "timezone": "America/New_York",
            "exists": 1,
            "deleted_at": null,
            "password_updated_at": "2023-12-18",
            "theme_support_level": 1,
            "currency": "₨"
        }
    },
    {
        "id": 5772248219930,
        "user_id": 422,
        "shopify_order_number": 1602,
        "customer_id": 7705583943962,
        "price": 26.68,
        "financial_status": "paid",
        "order_status": "Dispatched",
        "delivery_method": "Standard",
        "order_type": "Regular",
        "quantity_of_sheets": 1,
        "credit_used": null,
        "has_low_dpi": 0,
        "is_local_pickup": 0,
        "cancelled": 0,
        "credits_used": 0,
        "created_at": "December 28, 2023 1:13 am",
        "updated_at": "2023-12-28T06:33:10.000000Z",
        "notes": null,
        "sheets_download_status": "Ready For Download",
        "shopify_customer_name": null,
        "line_items_sum_quantity": "1",
        "edit_link": "https://zainab1sep.myshopify.com/apps/ganging-tool/editor/5772248219930?edit=true&edit_link=true",
        "customer": {
            "id": 7705583943962,
            "name": "znb khan"
        },
        "user": {
            "id": 422,
            "name": "zainab1sep.myshopify.com",
            "shop_name": "zainab1sep",
            "email": "shop@zainab1sep.myshopify.com",
            "contact_email": "zainabrahim089@gmail.com",
            "email_verified_at": null,
            "created_at": "2023-12-18T09:27:14.000000Z",
            "updated_at": "2023-12-28T07:09:20.000000Z",
            "shopify_grandfathered": 0,
            "shopify_namespace": null,
            "shopify_freemium": 0,
            "plan_id": 5,
            "timezone": "America/New_York",
            "exists": 1,
            "deleted_at": null,
            "password_updated_at": "2023-12-18",
            "theme_support_level": 1,
            "currency": "₨"
        }
    },
    {
        "id": 5772239438106,
        "user_id": 422,
        "shopify_order_number": 1601,
        "customer_id": 7705583943962,
        "price": 26.68,
        "financial_status": "paid",
        "order_status": "Cancelled",
        "delivery_method": "Standard",
        "order_type": "Regular",
        "quantity_of_sheets": 1,
        "credit_used": null,
        "has_low_dpi": 0,
        "is_local_pickup": 0,
        "cancelled": 1,
        "credits_used": 0,
        "created_at": "December 28, 2023 1:08 am",
        "updated_at": "2023-12-28T06:33:44.000000Z",
        "notes": null,
        "sheets_download_status": "Ready For Download",
        "shopify_customer_name": null,
        "line_items_sum_quantity": "1",
        "edit_link": "https://zainab1sep.myshopify.com/apps/ganging-tool/editor/5772239438106?edit=true&edit_link=true",
        "customer": {
            "id": 7705583943962,
            "name": "znb khan"
        },
        "user": {
            "id": 422,
            "name": "zainab1sep.myshopify.com",
            "shop_name": "zainab1sep",
            "email": "shop@zainab1sep.myshopify.com",
            "contact_email": "zainabrahim089@gmail.com",
            "email_verified_at": null,
            "created_at": "2023-12-18T09:27:14.000000Z",
            "updated_at": "2023-12-28T07:09:20.000000Z",
            "shopify_grandfathered": 0,
            "shopify_namespace": null,
            "shopify_freemium": 0,
            "plan_id": 5,
            "timezone": "America/New_York",
            "exists": 1,
            "deleted_at": null,
            "password_updated_at": "2023-12-18",
            "theme_support_level": 1,
            "currency": "₨"
        }
    },
    {
        "id": 5772231213338,
        "user_id": 422,
        "shopify_order_number": 1600,
        "customer_id": 7705583943962,
        "price": 26.68,
        "financial_status": "paid",
        "order_status": "Pending",
        "delivery_method": "Standard",
        "order_type": "Regular",
        "quantity_of_sheets": 1,
        "credit_used": null,
        "has_low_dpi": 0,
        "is_local_pickup": 0,
        "cancelled": 0,
        "credits_used": 0,
        "created_at": "December 28, 2023 1:04 am",
        "updated_at": "2023-12-28T06:05:57.000000Z",
        "notes": null,
        "sheets_download_status": "Downloaded",
        "shopify_customer_name": null,
        "line_items_sum_quantity": "1",
        "edit_link": "https://zainab1sep.myshopify.com/apps/ganging-tool/editor/5772231213338?edit=true&edit_link=true",
        "customer": {
            "id": 7705583943962,
            "name": "znb khan"
        },
        "user": {
            "id": 422,
            "name": "zainab1sep.myshopify.com",
            "shop_name": "zainab1sep",
            "email": "shop@zainab1sep.myshopify.com",
            "contact_email": "zainabrahim089@gmail.com",
            "email_verified_at": null,
            "created_at": "2023-12-18T09:27:14.000000Z",
            "updated_at": "2023-12-28T07:09:20.000000Z",
            "shopify_grandfathered": 0,
            "shopify_namespace": null,
            "shopify_freemium": 0,
            "plan_id": 5,
            "timezone": "America/New_York",
            "exists": 1,
            "deleted_at": null,
            "password_updated_at": "2023-12-18",
            "theme_support_level": 1,
            "currency": "₨"
        }
    },
    {
        "id": 5772039946522,
        "user_id": 422,
        "shopify_order_number": 1599,
        "customer_id": 7704005476634,
        "price": 26.68,
        "financial_status": "paid",
        "order_status": "Pending",
        "delivery_method": "Standard",
        "order_type": "Regular",
        "quantity_of_sheets": 1,
        "credit_used": null,
        "has_low_dpi": 1,
        "is_local_pickup": 0,
        "cancelled": 0,
        "credits_used": 0,
        "created_at": "December 27, 2023 23:20 pm",
        "updated_at": "2023-12-28T05:06:01.000000Z",
        "notes": null,
        "sheets_download_status": "Ready For Download",
        "shopify_customer_name": null,
        "line_items_sum_quantity": "1",
        "edit_link": "https://zainab1sep.myshopify.com/apps/ganging-tool/editor/5772039946522?edit=true&edit_link=true",
        "customer": {
            "id": 7704005476634,
            "name": "a a"
        },
        "user": {
            "id": 422,
            "name": "zainab1sep.myshopify.com",
            "shop_name": "zainab1sep",
            "email": "shop@zainab1sep.myshopify.com",
            "contact_email": "zainabrahim089@gmail.com",
            "email_verified_at": null,
            "created_at": "2023-12-18T09:27:14.000000Z",
            "updated_at": "2023-12-28T07:09:20.000000Z",
            "shopify_grandfathered": 0,
            "shopify_namespace": null,
            "shopify_freemium": 0,
            "plan_id": 5,
            "timezone": "America/New_York",
            "exists": 1,
            "deleted_at": null,
            "password_updated_at": "2023-12-18",
            "theme_support_level": 1,
            "currency": "₨"
        }
    },
    {
        "id": 5772027789594,
        "user_id": 422,
        "shopify_order_number": 1598,
        "customer_id": 7704005476634,
        "price": 40.6,
        "financial_status": "paid",
        "order_status": "Pending",
        "delivery_method": "Standard",
        "order_type": "Regular",
        "quantity_of_sheets": 2,
        "credit_used": null,
        "has_low_dpi": 1,
        "is_local_pickup": 0,
        "cancelled": 0,
        "credits_used": 0,
        "created_at": "December 27, 2023 23:06 pm",
        "updated_at": "2023-12-28T04:09:51.000000Z",
        "notes": null,
        "sheets_download_status": "Downloaded",
        "shopify_customer_name": null,
        "line_items_sum_quantity": "2",
        "edit_link": "https://zainab1sep.myshopify.com/apps/ganging-tool/editor/5772027789594?edit=true&edit_link=true",
        "customer": {
            "id": 7704005476634,
            "name": "a a"
        },
        "user": {
            "id": 422,
            "name": "zainab1sep.myshopify.com",
            "shop_name": "zainab1sep",
            "email": "shop@zainab1sep.myshopify.com",
            "contact_email": "zainabrahim089@gmail.com",
            "email_verified_at": null,
            "created_at": "2023-12-18T09:27:14.000000Z",
            "updated_at": "2023-12-28T07:09:20.000000Z",
            "shopify_grandfathered": 0,
            "shopify_namespace": null,
            "shopify_freemium": 0,
            "plan_id": 5,
            "timezone": "America/New_York",
            "exists": 1,
            "deleted_at": null,
            "password_updated_at": "2023-12-18",
            "theme_support_level": 1,
            "currency": "₨"
        }
    },
    {
        "id": 5771190173978,
        "user_id": 422,
        "shopify_order_number": 1597,
        "customer_id": 7704005476634,
        "price": 0,
        "financial_status": "paid",
        "order_status": "Dispatched",
        "delivery_method": "Standard",
        "order_type": "Regular",
        "quantity_of_sheets": 1,
        "credit_used": null,
        "has_low_dpi": 0,
        "is_local_pickup": 0,
        "cancelled": 0,
        "credits_used": 0,
        "created_at": "December 27, 2023 7:27 am",
        "updated_at": "2023-12-28T04:10:08.000000Z",
        "notes": null,
        "sheets_download_status": "Downloaded",
        "shopify_customer_name": null,
        "line_items_sum_quantity": "1",
        "edit_link": "https://zainab1sep.myshopify.com/apps/ganging-tool/editor/5771190173978?edit=true&edit_link=true",
        "customer": {
            "id": 7704005476634,
            "name": "a a"
        },
        "user": {
            "id": 422,
            "name": "zainab1sep.myshopify.com",
            "shop_name": "zainab1sep",
            "email": "shop@zainab1sep.myshopify.com",
            "contact_email": "zainabrahim089@gmail.com",
            "email_verified_at": null,
            "created_at": "2023-12-18T09:27:14.000000Z",
            "updated_at": "2023-12-28T07:09:20.000000Z",
            "shopify_grandfathered": 0,
            "shopify_namespace": null,
            "shopify_freemium": 0,
            "plan_id": 5,
            "timezone": "America/New_York",
            "exists": 1,
            "deleted_at": null,
            "password_updated_at": "2023-12-18",
            "theme_support_level": 1,
            "currency": "₨"
        }
    },
    {
        "id": 5771184832794,
        "user_id": 422,
        "shopify_order_number": 1596,
        "customer_id": 7704005476634,
        "price": 638,
        "financial_status": "paid",
        "order_status": "Pending",
        "delivery_method": "Standard",
        "order_type": "Bulk",
        "quantity_of_sheets": 1,
        "credit_used": null,
        "has_low_dpi": 0,
        "is_local_pickup": 0,
        "cancelled": 0,
        "credits_used": 0,
        "created_at": "December 27, 2023 7:18 am",
        "updated_at": "2023-12-27T12:18:11.000000Z",
        "notes": null,
        "sheets_download_status": "Pre-Rendering",
        "shopify_customer_name": null,
        "line_items_sum_quantity": null,
        "edit_link": "https://zainab1sep.myshopify.com/apps/ganging-tool/editor/5771184832794?edit=true&edit_link=true",
        "customer": {
            "id": 7704005476634,
            "name": "a a"
        },
        "user": {
            "id": 422,
            "name": "zainab1sep.myshopify.com",
            "shop_name": "zainab1sep",
            "email": "shop@zainab1sep.myshopify.com",
            "contact_email": "zainabrahim089@gmail.com",
            "email_verified_at": null,
            "created_at": "2023-12-18T09:27:14.000000Z",
            "updated_at": "2023-12-28T07:09:20.000000Z",
            "shopify_grandfathered": 0,
            "shopify_namespace": null,
            "shopify_freemium": 0,
            "plan_id": 5,
            "timezone": "America/New_York",
            "exists": 1,
            "deleted_at": null,
            "password_updated_at": "2023-12-18",
            "theme_support_level": 1,
            "currency": "₨"
        }
    }
]